# Generated by Django 4.2.4 on 2023-11-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('famous_foods', models.TextField()),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.URLField(default='https://example.com/default_image.jpg')),
            ],
        ),
    ]
